file_format: "1"
id: corne
name: CORNE
type: shield
url: https://github.com/Bastardkb/TBK-Mini
requires: [Nice!Nano]
exposes: []
features:
  - keys
  - underglow
  - backlight
siblings:
  - corne_left
  - corne_right
